# Generated by Django 5.0 on 2025-09-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_profile_is_approved'),
        ('chat', '0002_auto_20230916_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_sender__61a5fc_idx',
            old_name='chat_messag_sender__f0a5a3_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_is_read_872c73_idx',
            old_name='chat_messag_is_read_4c7b30_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp'], name='chat_messag_timesta_6494d7_idx'),
        ),
    ]
