# Generated by Django 5.0 on 2025-09-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_approve_expert', 'Can approve expert accounts')]},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether the expert account is approved.'),
        ),
    ]
