# Generated by Django 5.0 on 2025-09-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_update', 'Project Update'), ('request_accepted', 'Request Accepted'), ('new_rating', 'New Rating'), ('new_reaction', 'New Reaction'), ('message', 'Message'), ('payment', 'Payment'), ('system', 'System'), ('service', 'Service')], default='system', help_text='Type of notification', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
